### ISSUE TITLE
mouse.left_click() returns False, no action

### ISSUE THREAD

**Issue by crackwitz** [winstxnhdw/KeyWin#4]
I just installed and tried this package, then ran this code in an interactive interpreter:
```none
>>> from keywin import mouse
>>> mouse.left_click()
False
>>>
```
No click happened.

I see no caveats mentioned or anything else I'd need to do to make this work.

**Comment by winstxnhdw** [comment]
Hmm.. Strange. You are running this on Windows, yes?

**Comment by crackwitz** [comment]
Windows 10, 22H2, Python 3.11 or 3.12

It doesn't happen to need elevation or anything, right?

Calling `SendInput` WinAPI directly works just fine. Doesn't respect my swapped mouse buttons but I'd been aware of that.

**Comment by winstxnhdw** [comment]
Hey, sorry for the wait. I finally found enough time to narrow down the problem. I have included some integration tests so that such a problem would not occur again. Thanks for finding this.
